---
version: '3.9'
services:
  build:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.devel
    entrypoint: /usr/bin/tail -f /dev/null
    volumes:
      - .:/llvm-tutorial
    working_dir: /llvm-tutorial