---
version: '3.9'
services:
  develop:
    image: llvm-tutorial:develop
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.develop
    entrypoint: ["/usr/bin/tail", "-f", "/dev/null"]
    volumes:
      - .:/llvm-tutorial
    working_dir: /llvm-tutorial
